
api:
    cat-facts:
        url: https://cat-fact.herokuapp.com
        readTimeout: 1s
        connectTimeout: 1s
        secure: true
    joke:
        url: https://api.chucknorris.io
        readTimeout: 2s
        connectTimeout: 2s
        secure: true
    postcode:
        url: https://api.postcodes.io
        readTimeout: 1500ms
        connectTimeout: 500ms
        secure: true
management:
    endpoints:
        web:
            exposure:
                include: health, metrics, info, prometheus
spring:
    application:
        name: rest-template-example
    sleuth:
        sampler:
            probability: 1